$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: localai-deployment-chat-endpoint
endpoint_name: localai-endpoint
model:
  azureml:phi-2:1
model_mount_path: /build/models
environment:
  image: quay.io/go-skynet/local-ai:latest
  inference_config:
    liveness_route:
      port: 8080
      path: /v1/models/
    readiness_route:
      port: 8080
      path: /v1/models/
    scoring_route:
      port: 8080
      path: /v1/chat/completions
instance_type: Standard_DS5_v2
instance_count: 1
request_settings:
  request_timeout_ms: 100000
